- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
      - neovim
      - node
      - zsh
  tasks:
    - name: Include core setup tasks
      ansible.builtin.include_tasks: tasks/core.yml
      tags:
        - install
        - neovim
        - core

    - name: Include SSH setup tasks
      ansible.builtin.include_tasks: tasks/ssh.yml
      tags:
        - dotfiles
        - install
        - ssh

    - name: Include Git setup tasks
      ansible.builtin.include_tasks: tasks/git.yml
      tags:
        - git-personal

    - name: Include Neovim setup tasks
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags:
        - install
        - neovim
    - name: Include Node setup tasks
      ansible.builtin.include_tasks: tasks/node.yml
      tags:
        - install
        - node
    - name: Include Npm packages tasks
      ansible.builtin.include_tasks: tasks/npm-packages.yml
      tags:
        - install
        - node
    - name: Include Zsh setup tasks
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags:
        - install
        - dotfiles
        - zsh

    #- include: tasks/node.yml
    #- include: tasks/zsh.yml
    #- include: tasks/slack.yml
    #- include: tasks/personal-projects.yml
    #- include: tasks/nvim.yml
    #- include: tasks/brave.yml
    #- include: tasks/debugger.yml
    #- include: tasks/dotfiles.yml
    #- include: tasks/productivity-tools.yml
    #- include: tasks/lsp.yml
