- hosts: localhost
  vars:
    source_key: "{{ playbook_dir }}/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: Include core Setup Tasks
      ansible.builtin.include_tasks: tasks/core.yml
      tags:
        - install
        - neovim
        - core
    - name: Include SSH Setup Tasks
      ansible.builtin.include_tasks: tasks/ssh.yml
      tags:
        - dotfiles
        - install
        - ssh
    - name: Include Git Setup Tasks
      ansible.builtin.include_tasks: tasks/git.yml
      tags:
        - git-personal
    - name: Include Neovim Setup Tasks
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags:
        - install
        - neovim
    - name: Include Dotnet Setup Tasks
      ansible.builtin.include_tasks: tasks/dotnet.yml
      tags:
        - install
        - dotnet
    - name: Include Node Setup Tasks
      ansible.builtin.include_tasks: tasks/node.yml
      tags:
        - install
        - node
    - name: Include Npm Packages Setup Tasks
      ansible.builtin.include_tasks: tasks/npm-packages.yml
      tags:
        - install
        - node
    - name: Include Zsh Setup Tasks
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags:
        - install
        - dotfiles
        - zsh
    - name: Include Brave Setup Tasks
      ansible.builtin.include_tasks: tasks/brave.yml
      tags:
        - install
        - brave
    - name: Include Dotfiles Setup Tasks
      ansible.builtin.include_tasks: tasks/brave.yml
      tags:
        - install
        - brave
    - name: Include Productivity Tools Setup Tasks
      ansible.builtin.include_tasks: tasks/productivity-tools.yml
      tags:
        - install
        - productivity
