- name: Install System Packages 1 ("make", "gcc", "ripgrep", "unzip", "git", "xclip", "curl")
  become: true
  apt:
    name: ["build-essential", "cmake", "unzip", "git", "curl"]
    state: present
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 ("pavucontrol", "htop")
  become: true
  apt:
    name: ["pavucontrol", "htop"]
    state: present
  tags:
    - install
    - core
