- name: Install System Packages 1 ("build-essential", "pkg-config", "cmake", "unzip", "git", "curl", "libfontconfig1-dev", "libfreetype6-dev", "libx11-dev", "libxft-dev", "libxinerama-dev")
  become: true
  apt:
    name: ["build-essential", "pkg-config", "cmake", "unzip", "git", "curl", "libfontconfig1-dev", "libfreetype6-dev", "libx11-dev", "libxft-dev", "libxinerama-dev"]
    state: present
  tags:
    - install
    - neovim
    - st
    - core

- name: Install System Packages 2 ("pavucontrol", "htop")
  become: true
  apt:
    name: ["pavucontrol", "htop"]
    state: present
  tags:
    - install
    - core
