- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Add Docker repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Update package lists after adding repository
  apt:
    update_cache: yes
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Install Docker and plugins
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: present
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Ensure Docker group exists
  group:
    name: docker
    state: present
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Add user to Docker group
  user:
    name: "stasnocap"
    groups: docker
    append: yes
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
  become: true
  tags:
    - docker
    - wsl
    - home

- name: Apply new group membership
  command: newgrp docker
  changed_when: false
  become: true
  tags:
    - docker
    - wsl
    - home
