- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  become: true
  tags:
    - node
    - wsl
    - home

- name: Install Typescript
  npm:
    name: typescript
    global: yes
  become: true
  tags:
    - node
    - wsl
    - home

- name: Install Html lsp
  npm:
    name: vscode-langservers-extracted
    global: yes
  become: true
  tags:
    - node
    - wsl
    - home
